<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="PDFtoImage" Version="5.4.0" />
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
  </ItemGroup>

</Project>
